### ISSUE TITLE
Option to display the entire schedule for today

### ISSUE THREAD

**Issue by psyclone20** [DhruvPatel01/indian-tv-schedule-api#1]
By default, the API shows only the current and upcoming shows for today. An option to get all the shows for today from the beginning would be helpful.
I've looked around on burrp and the URL for the entire day's schedule just has a **/1** at the end.

e.g. http://tv.burrp.com/channel/HBO/8/2017-10-18%200:0:0/1

**Comment by DhruvPatel01** [comment]
Yes you are right. That feature might be useful. As you said implementing it would also be trivial task. But these days I am busy. So unfortunately I will probably not be able to implement and test it till December. (Actually I am surprised that the code still works, i.e. burrp hasn't changed in three years. :) ) 

Anyway thanks for bringing it up.
